# Generated by Django 3.2.16 on 2022-12-12 15:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название')),
                ('slug', models.SlugField(blank=True, help_text='Слаг', max_length=200, unique=True, verbose_name='слаг')),
                ('weight', models.IntegerField(blank=True, default=100, help_text='Вес категории', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32766)])),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название')),
                ('slug', models.SlugField(blank=True, help_text='Слаг', max_length=200, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='изображение')),
                ('text', models.TextField(blank=True, default='Sample Text', help_text='Описание товара', verbose_name='описание')),
                ('category', models.ForeignKey(help_text='Категория товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homepage.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(help_text='Теги товара', related_name='items', to='homepage.Tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'default_related_name': 'items',
            },
        ),
    ]
