# Generated by Django 3.2.16 on 2022-12-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20221218_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proglanguage',
            options={'default_related_name': 'categories', 'verbose_name': 'язык программирования', 'verbose_name_plural': 'языки программирования'},
        ),
        migrations.RemoveField(
            model_name='proglanguage',
            name='weight',
        ),
    ]
