# Generated by Django 3.2.16 on 2022-12-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0007_auto_20221218_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='proglanguage',
            options={'default_related_name': 'prog_languages', 'verbose_name': 'programming language', 'verbose_name_plural': 'programming languages'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='edited on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='Post under which the comment is written', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homepage.post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='prev_comment',
            field=models.ForeignKey(blank=True, help_text='Comment to which this comment is replying to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homepage.comment', verbose_name='above comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, help_text='Post author', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, help_text='Your code', verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prog_language',
            field=models.ForeignKey(help_text='Programming language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='homepage.proglanguage', verbose_name='programming language'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='Post tags', related_name='posts', to='homepage.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Post description', verbose_name='description'),
        ),
    ]
