# Generated by Django 3.2.16 on 2022-12-19 18:52

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0007_auto_20221218_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='proglanguage',
            options={'default_related_name': 'prog_languages', 'verbose_name': 'programming language', 'verbose_name_plural': 'programming languages'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='post',
            name='age_of_post',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='дата создания поста', verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.FloatField(blank=True, default=0, help_text='популярность поста = просмотры \\ время жизни поста', verbose_name='популярность'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='edited on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='Post under which the comment is written', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homepage.post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='prev_comment',
            field=models.ForeignKey(blank=True, help_text='Comment to which this comment is replying to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homepage.comment', verbose_name='above comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, help_text='Post author', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, help_text='Your code', verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prog_language',
            field=models.ForeignKey(help_text='Programming language', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='homepage.proglanguage', verbose_name='programming language'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(help_text='Post tags', related_name='posts', to='homepage.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Code description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug', max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug', max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
