# Generated by Django 3.2.16 on 2022-12-19 18:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20221218_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proglanguage',
            options={'default_related_name': 'prog_languages', 'verbose_name': 'язык программирования', 'verbose_name_plural': 'языки программирования'},
        ),
        migrations.AddField(
            model_name='post',
            name='age_of_post',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='дата создания поста', verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.FloatField(blank=True, default=0, help_text='популярность поста = просмотры \\ время жизни поста', verbose_name='популярность'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='просмотры'),
        ),
    ]
