# Generated by Django 3.2.16 on 2022-12-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20221219_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='prev_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, help_text='The head comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='homepage.comment', verbose_name='parent comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_comment',
            field=models.ForeignKey(blank=True, help_text='Comment to which this comment is replying to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replying_comments', to='homepage.comment', verbose_name='above comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='popularity',
            field=models.FloatField(blank=True, default=0, help_text='популярность поста = просмотры / время жизни поста', verbose_name='популярность'),
        ),
    ]
