# Generated by Django 3.2.16 on 2022-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20221219_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Code description', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug', max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug', max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
