# Generated by Django 3.2.16 on 2022-12-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20221222_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age_of_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='proglanguage',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(help_text='Your code', verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
    ]
