# Generated by Django 3.2.16 on 2022-12-22 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20221222_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_of_post',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AddField(
            model_name='proglanguage',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(blank=True, help_text='Your code', verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='proglanguage',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='name'),
        ),
    ]
