# Generated by Django 3.2.16 on 2022-12-11 10:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Не более 150 символов', max_length=150, verbose_name='имя пользователя')),
                ('email', models.EmailField(help_text='Не более 254 символов', max_length=254, unique=True, verbose_name='электронная почта')),
                ('first_name', models.CharField(blank=True, help_text='Не более 254 символов', max_length=254, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, help_text='Не более 254 символов', max_length=254, null=True, verbose_name='фамилия')),
                ('about_me', models.TextField(blank=True, default='Sample Text', help_text='Обо мне', verbose_name='описание')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'default_related_name': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
