# Generated by Django 3.2.16 on 2022-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221211_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m', verbose_name='изображение профиля'),
        ),
    ]
