# Generated by Django 3.2.16 on 2022-12-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221222_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, default='no bio yet', verbose_name='about me'),
        ),
    ]
